#!/bin/bash

Help()
{
   # Display Help
   echo "This script converts all alert runbooks to adoc for inclusion in the"
   echo "OpenShift documentation"
   echo
   echo "Syntax: convert-runbook-to-doc.sh <doc dir>"
   echo "arguments:"
   echo "doc dir: path to the openshift-docs clone"
   echo "         runbooks wil be created in <doc dir>/monitoring/alert-runbooks/"
   echo
}

if ! command -v kramdoc &> /dev/null
then
    echo "kramdoc could not be found"
    exit 1
fi


if [ -z "$1" ]
  then
    echo "No output dir supplied"
    Help
    exit 1
fi
docdir="$1"
runbook="monitoring/alert-runbooks.adoc"

gitrev=$(git rev-parse HEAD 2>/dev/null)
if [ $? -ne 0 ]
then
    gitrev="master"
fi

set -e

cat > "$docdir/$runbook" << EOF
// This file and the runbooks were generated by https://github.com/openshift/runbooks/tree/$gitrev/hack/$(basename "$0")
[id="alert-runbooks"]
= Alert Runbooks
include::modules/attributes-openshift-dedicated.adoc[]

toc::[]

EOF

find alerts -name "*.md" -print0 | while IFS= read -rd $'\0' file; do
    alertname=$(basename "$file" ".md")
    echo "[id=\"$alertname\"]" | tr '[:upper:]' '[:lower:]' >> "$docdir/$runbook"
    kramdoc --heading-offset=1 -o - "$file" | \
        sed  '/===\+/i \[discrete\]' | \
        sed 's/\[,console\]/\[source,terminal\]/' >> "$docdir/$runbook"
    echo "" >> "$docdir/$runbook"
done
